name: Build & Test

on:
  push:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: 🔢 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📶 Install
        run: |
          npm install
        env:
          CI: true

      - name: 🧪 Test
        run: |
          npm run test:ci
          cat ./coverage/lcov.info
        env:
          CI: true

      - name: 🔊 SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        # only run SonarCloud in the context of the main repo, not in forks
        if: ${{ github.repository == 'se310-Team4/KKDZ' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: 🔧 Build
        run: |
          npm run build
        env:
          CI: true

      # if tests pass and we're on the mainline branch (and not in a forked repo), then deploy the client to the website
      - name: 🚀 Deploy
        if: ${{ github.repository == 'se310-Team4/KKDZ' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          folder: src
          branch: gh-pages
