name: Build & Test

on:
  push:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: 🔢 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📶 Install
        run: |
          npm install
        env:
          CI: true

      - name: 🧪 Test
        run: |
          npm run test:ci
        env:
          CI: true

      - name: 📈 Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔧 Build
        run: |
          npm run build
        env:
          CI: true

      # if tests pass and we're on the mainline brand, deploy the client to the website
      - name: 🚀 Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository-name: se310-Team4.github.io
          folder: dist
          branch: main
